spring.application.name=mallapi

spring.datasource.url=jdbc:mariadb://root:SprrdToyEpPnjTITlVhRHWerNFTpCvOB@kodama.proxy.rlwy.net:10629/railway
spring.datasource.username=root
spring.datasource.password=SprrdToyEpPnjTITlVhRHWerNFTpCvOB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

