spring.application.name=mallapi

spring.datasource.url=jdbc:mariadb://kodama.proxy.rlwy.net:42841/railway
spring.datasource.username=root
spring.datasource.password=pCnPvNYcRoudHkBliUwPkBNtVKHCvTLX
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.port=8080

